version: "3.8"

services:
  zookeeper:
    image: itsaur/zookeeper-replicated:latest
    hostname: "{{.Node.Hostname}}-zookeeper"
    environment:
      REPLICAS: 3
      SERVICE_NAME: zookeeper
    networks:
      - sorl_net
    deploy:
      replicas: 3
  
  # solr:
  #   image: solr:latest
  #   hostname: "{{.Node.Hostname}}-solr"
  #   ports:
  #     - "8983:8983"
  #   networks:
  #     - sorl_net
  #   volumes:
  #     - data:/opt/solr/server/solr/tech_products
  #   entrypoint:
  #     - docker-entrypoint.sh
  #     - -c
  #     - -z 
  #     - zookeeper:2181
  #   deploy:
  #     mode: global

volumes:
  data:

networks:
  sorl_net: